project:
  type: website
  output-dir: docs

website:
  title: "Gloria Nana Ama Boadi"
  navbar:
    left:
      - href: index.qmd
        text: "{{< fa house >}} Home"
      - href: CV.qmd
        text: "{{< fa user-tie >}} CV"
        
        
    right:
      - href: Contact.qmd
        text: "{{< fa envelope >}} Contact"
      - href: https://github.com/clairl
        icon: github
      - href: https://twitter.com/Luc_Clair
        icon: twitter    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

